CREATE TABLE joke(
	joke_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	title VARCHAR(200) DEFAULT "",
	content TEXT,
	stamps VARCHAR(200),
	likes INT UNSIGNED DEFAULT 0,
	dislike INT UNSIGNED DEFAULT 0,
	url VARCHAR(200) DEFAULT "",
	PRIMARY KEY (joke_id)
)ENGINE=InnoDB, CHARSET=UTF8;


CREATE TABLE tiezi(
	tiezi_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	parent_id INT UNSIGNED NOT NULL DEFAULT 0,
	title VARCHAR(200) DEFAULT "",
	content TEXT,
	tiezi_date TIMESTAMP,
	date_entered TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(tiezi_id)
)