CREATE TABLE words(
    w_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    w_val VARCHAR(50) DEFAULT "",
    w_desc TEXT DEFAULT "",
    w_md5 CHAR(32),
    w_date_entered TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(w_id)
)ENGINE=MyISAM,CHARSET=UTF8;